terminal(e([J,J,J,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,J,J,J,J,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,J,J,J,J,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,J,J,J,J,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    J,J,J,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,J,J,J,J,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,J,J,J,J,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,J,J,J,J,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    J,J,J,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,J,J,J,J,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,J,J,J,J,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,J,J,J,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    J,J,J,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,J,J,J,J,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,J,J,J,J,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,J,J,J,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    J,J,J,J,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,J,J,J,J,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,J,J,J,J,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,J,J,J,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    J,J,J,J,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,J,J,J,J,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,J,J,J,J,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,J,J,J], J)) :- J=w ; J=b.

% colunas
terminal(e([J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    J,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,J,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,J,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,J,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,J,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,J,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,J], J)) :- J=w ; J=b.


% diagonais esquerda para a direita

terminal(e([J,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,J,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,J,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    J,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,J,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,v,v,J], J)) :- J=w ; J=b.

% diagonais direita para a esquerda
terminal(e([v,v,v,v,v,v,J,
    v,v,v,v,v,J,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,J,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,J,v,v,v,v,v,
    J,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,J,
    v,v,v,v,v,J,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,J,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,J,v,v,v,v,v,
    J,v,v,v,v,v,v,
    v,v,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,v,J,
    v,v,v,v,v,J,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,v,J,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,v,J,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,J,v,v,v,v,v], J)) :- J=w ; J=b.
terminal(e([v,v,v,v,v,v,v,
    v,v,v,v,v,v,v,
    v,v,v,J,v,v,v,
    v,v,J,v,v,v,v,
    v,J,v,v,v,v,v,
    J,v,v,v,v,v,v], J)) :- J=w ; J=b.


